name: Notify on Pull Request

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@v0.4.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: 'Pull Request Opened: ${{ github.event.pull_request.html_url }}'
